### ISSUE TITLE
Follow the install but there is error and never success.

### ISSUE THREAD

**Issue by mactrash** [kitconcept/volto-light-theme#425]
/home/plone/.nvm/versions/node/v20.18.0/lib/node_modules/corepack/dist/lib/corepack.cjs:22147
      throw new UsageError(`Invalid package.json in ${import_path8.default.relative(initialCwd, manifestPath)}`);
            ^

UsageError: Invalid package.json in package.json
    at loadSpec (/home/plone/.nvm/versions/node/v20.18.0/lib/node_modules/corepack/dist/lib/corepack.cjs:22147:13)
    at async Engine.findProjectSpec (/home/plone/.nvm/versions/node/v20.18.0/lib/node_modules/corepack/dist/lib/corepack.cjs:22348:22)
    at async Engine.executePackageManagerRequest (/home/plone/.nvm/versions/node/v20.18.0/lib/node_modules/corepack/dist/lib/corepack.cjs:22404:24)
    at async Object.runMain (/home/plone/.nvm/versions/node/v20.18.0/lib/node_modules/corepack/dist/lib/corepack.cjs:23096:5) {
  clipanion: { type: 'usage' }
}

**Comment by mactrash** [comment]
I now try this with Volto 18 and problem gone
