### ISSUE TITLE
Volto 18 how can I correct install this, please update document 

### ISSUE THREAD

**Issue by mactrash** [kitconcept/volto-light-theme#426]
I follow the step added dependencies and addon 

make install etc

And got below when try to run with pnpm start

TypeError: Cannot read properties of undefined (reading 'modulePath')
    at defaultModify (/mnt/HDD2/VOLTO/test-com/frontend/core/packages/volto/razzle.config.js:331:57)
    at modifyWebpackConfig (/mnt/HDD2/VOLTO/test-com/frontend/core/packages/volto/razzle.config.js:457:27)
    at /mnt/HDD2/VOLTO/test-com/frontend/node_modules/.pnpm/razzle@4.2.18_@babel+core@7.26.0_babel-preset-razzle@4.2.18_eslint@8.57.1_html-webpack-plugin_nvra5mldcm7qyfv3nq5oebxjbi/node_modules/razzle/config/createConfigAsync.js:1069:22
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
/mnt/HDD2/VOLTO/test-com/frontend/core/packages/volto:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @plone/volto@18.0.0-alpha.47 start: `make build-deps && razzle start`
Exit status 1
 ELIFECYCLE  Command failed with exit code 1.

**Comment by davisagli** [comment]
@sneridagh Is this because the theme needs to be configured a different way with a pnpm-based project?

**Comment by mactrash** [comment]
> @sneridagh Is this because the theme needs to be configured a different way with a pnpm-based project?

I don't sure, yarn pnpm ... already make me confuse. maybe now is not the time to study

**Comment by sneridagh** [comment]
@mactrash I think you detected a problem in the instructions. `@kitconcept/volto-light-theme` is an add-on too, and should be declared as one:

```
const addons = ['@kitconcept/volto-light-theme'];
const theme = '@kitconcept/volto-light-theme';

module.exports = {
  addons,
  theme,
};
```

Sorry about that, I will update the instructions right now.

**Comment by sneridagh** [comment]
@mactrash I double check, the instructions are correct, but could be confusing. We would improve them soon.
Make sure that both are specified.

**Comment by mactrash** [comment]
@sneridagh please forgive me, I cam complete new to Volto 

Is that 

1. add 

"dependencies": {
    "@eeacms/volto-accordion-block": "^10.4.0",
    "@kitconcept/volto-button-block": "^2.3.1",
    "@kitconcept/volto-dsgvo-banner": "^1.3.0",
    "@kitconcept/volto-heading-block": "^2.4.0",
    "@kitconcept/volto-highlight-block": "^3.0.0",
    "@kitconcept/volto-introduction-block": "^1.0.0",
    "@kitconcept/volto-separator-block": "^4.0.0",
    "@kitconcept/volto-slider-block": "^6.0.0",
    "@kitconcept/volto-light-theme": "^2.0.0",
  }

to /frontend/package.json 

2. modify

/frontend/volto.config.js

as
 
const addons = ['@kitconcept/volto-light-theme'];
const theme = '@kitconcept/volto-light-theme';

module.exports = {
  addons,
  theme,
};

3. pnpm install

no error

4. HOST=x.x.x.x pnpm start

and result 

sswp> !!! Script exited with code 1

And frontend not started

**Comment by iRohitSingh** [comment]
I also tried setting up vlt in frest project generated by cookieplone and getting this error

```
ERROR in ../../../node_modules/.pnpm/@kitconcept+volto-light-theme@5.0.1_@eeacms+volto-accordion-block@10.4.6_@kitconcept+volto-bu_x5bo2ca4vy463dmo6jnv33c3tm/node_modules/@kitconcept/volto-light-theme/src/theme/main.scss (../../../node_modules/.pnpm/css-loader@5.2.7_webpack@5.90.1_esbuild@0.24.0_/node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[6].use[1]!../../../node_modules/.pnpm/postcss-loader@4.3.0_postcss@8.4.31_webpack@5.90.1_esbuild@0.24.0_/node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[6].use[2]!../../../node_modules/.pnpm/resolve-url-loader@3.1.5/node_modules/resolve-url-loader/index.js??ruleSet[1].rules[6].use[3]!../../../node_modules/.pnpm/sass-loader@10.5.2_sass@1.80.6_webpack@5.90.1_esbuild@0.24.0_/node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[6].use[4]!../../../node_modules/.pnpm/@kitconcept+volto-light-theme@5.0.1_@eeacms+volto-accordion-block@10.4.6_@kitconcept+volto-bu_x5bo2ca4vy463dmo6jnv33c3tm/node_modules/@kitconcept/volto-light-theme/src/theme/main.scss)
Module build failed (from ../../../node_modules/.pnpm/sass-loader@10.5.2_sass@1.80.6_webpack@5.90.1_esbuild@0.24.0_/node_modules/sass-loader/dist/cjs.js):
SassError: Can't find stylesheet to import.
  ╷
2 │ @import 'addonsThemeCustomizationsVariables';
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  ../../../node_modules/.pnpm/@kitconcept+volto-light-theme@5.0.1_@eeacms+volto-accordion-block@10.4.6_@kitconcept+volto-bu_x5bo2ca4vy463dmo6jnv33c3tm/node_modules/@kitconcept/volto-light-theme/src/theme/main.scss 2:9  root stylesheet
SassError: SassError: Can't find stylesheet to import.
  ╷
2 │ @import 'addonsThemeCustomizationsVariables';
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  ../../../node_modules/.pnpm/@kitconcept+volto-light-theme@5.0.1_@eeacms+volto-accordion-block@10.4.6_@kitconcept+volto-bu_x5bo2ca4vy463dmo6jnv33c3tm/node_modules/@kitconcept/volto-light-theme/src/theme/main.scss 2:9  root stylesheet
    at /Users/rohitkumar/Desktop/my-project/frontend/node_modules/.pnpm/sass-loader@10.5.2_sass@1.80.6_webpack@5.90.1_esbuild@0.24.0_/node_modules/sass-loader/dist/index.js:49:16
    at Function.call$2 (/Users/rohitkumar/Desktop/my-project/frontend/node_modules/.pnpm/sass@1.80.6/node_modules/sass/sass.dart.js:126797:16)
    at render_closure1.call$2 (/Users/rohitkumar/Desktop/my-project/frontend/node_modules/.pnpm/sass@1.80.6/node_modules/sass/sass.dart.js:108247:12)
    at _RootZone.runBinary$3$3 (/Users/rohitkumar/Desktop/my-project/frontend/node_modules/.pnpm/sass@1.80.6/node_modules/sass/sass.dart.js:39649:18)
    at _FutureListener.handleError$1 (/Users/rohitkumar/Desktop/my-project/frontend/node_modules/.pnpm/sass@1.80.6/node_modules/sass/sass.dart.js:38167:21)
    at _Future__propagateToListeners_handleError.call$0 (/Users/rohitkumar/Desktop/my-project/frontend/node_modules/.pnpm/sass@1.80.6/node_modules/sass/sass.dart.js:38482:49)
    at Object._Future__propagateToListeners (/Users/rohitkumar/Desktop/my-project/frontend/node_modules/.pnpm/sass@1.80.6/node_modules/sass/sass.dart.js:5217:77)
    at _Future._completeError$2 (/Users/rohitkumar/Desktop/my-project/frontend/node_modules/.pnpm/sass@1.80.6/node_modules/sass/sass.dart.js:38333:9)
    at _AsyncAwaitCompleter.completeError$2 (/Users/rohitkumar/Desktop/my-project/frontend/node_modules/.pnpm/sass@1.80.6/node_modules/sass/sass.dart.js:37931:12)
    at Object._asyncRethrow (/Users/rohitkumar/Desktop/my-project/frontend/node_modules/.pnpm/sass@1.80.6/node_modules/sass/sass.dart.js:4995:17)
    at /Users/rohitkumar/Desktop/my-project/frontend/node_modules/.pnpm/sass@1.80.6/node_modules/sass/sass.dart.js:28641:20
    at _wrapJsFunctionForAsync_closure.$protected (/Users/rohitkumar/Desktop/my-project/frontend/node_modules/.pnpm/sass@1.80.6/node_modules/sass/sass.dart.js:5020:15)
    at _wrapJsFunctionForAsync_closure.call$2 (/Users/rohitkumar/Desktop/my-project/frontend/node_modules/.pnpm/sass@1.80.6/node_modules/sass/sass.dart.js:37950:12)
    at _awaitOnObject_closure0.call$2 (/Users/rohitkumar/Desktop/my-project/frontend/node_modules/.pnpm/sass@1.80.6/node_modules/sass/sass.dart.js:37944:25)
    at _RootZone.runBinary$3$3 (/Users/rohitkumar/Desktop/my-project/frontend/node_modules/.pnpm/sass@1.80.6/node_modules/sass/sass.dart.js:39649:18)
    at _FutureListener.handleError$1 (/Users/rohitkumar/Desktop/my-project/frontend/node_modules/.pnpm/sass@1.80.6/node_modules/sass/sass.dart.js:38167:21)
    at _Future__propagateToListeners_handleError.call$0 (/Users/rohitkumar/Desktop/my-project/frontend/node_modules/.pnpm/sass@1.80.6/node_modules/sass/sass.dart.js:38482:49)
    at Object._Future__propagateToListeners (/Users/rohitkumar/Desktop/my-project/frontend/node_modules/.pnpm/sass@1.80.6/node_modules/sass/sass.dart.js:5217:77)
    at _Future._completeError$2 (/Users/rohitkumar/Desktop/my-project/frontend/node_modules/.pnpm/sass@1.80.6/node_modules/sass/sass.dart.js:38333:9)
    at _AsyncAwaitCompleter.completeError$2 (/Users/rohitkumar/Desktop/my-project/frontend/node_modules/.pnpm/sass@1.80.6/node_modules/sass/sass.dart.js:37931:12)
    at Object._asyncRethrow (/Users/rohitkumar/Desktop/my-project/frontend/node_modules/.pnpm/sass@1.80.6/node_modules/sass/sass.dart.js:4995:17)
    at /Users/rohitkumar/Desktop/my-project/frontend/node_modules/.pnpm/sass@1.80.6/node_modules/sass/sass.dart.js:20755:20
    at _wrapJsFunctionForAsync_closure.$protected (/Users/rohitkumar/Desktop/my-project/frontend/node_modules/.pnpm/sass@1.80.6/node_modules/sass/sass.dart.js:5020:15)
    at _wrapJsFunctionForAsync_closure.call$2 (/Users/rohitkumar/Desktop/my-project/frontend/node_modules/.pnpm/sass@1.80.6/node_modules/sass/sass.dart.js:37950:12)
    at _awaitOnObject_closure0.call$2 (/Users/rohitkumar/Desktop/my-project/frontend/node_modules/.pnpm/sass@1.80.6/node_modules/sass/sass.dart.js:37944:25)
    at _RootZone.runBinary$3$3 (/Users/rohitkumar/Desktop/my-project/frontend/node_modules/.pnpm/sass@1.80.6/node_modules/sass/sass.dart.js:39649:18)
    at _FutureListener.handleError$1 (/Users/rohitkumar/Desktop/my-project/frontend/node_modules/.pnpm/sass@1.80.6/node_modules/sass/sass.dart.js:38167:21)
    at _Future__propagateToListeners_handleError.call$0 (/Users/rohitkumar/Desktop/my-project/frontend/node_modules/.pnpm/sass@1.80.6/node_modules/sass/sass.dart.js:38482:49)
    at Object._Future__propagateToListeners (/Users/rohitkumar/Desktop/my-project/frontend/node_modules/.pnpm/sass@1.80.6/node_modules/sass/sass.dart.js:5217:77)
    at _Future._completeError$2 (/Users/rohitkumar/Desktop/my-project/frontend/node_modules/.pnpm/sass@1.80.6/node_modules/sass/sass.dart.js:38333:9)
    at _AsyncAwaitCompleter.completeError$2 (/Users/rohitkumar/Desktop/my-project/frontend/node_modules/.pnpm/sass@1.80.6/node_modules/sass/sass.dart.js:37931:12)
    at Object._asyncRethrow (/Users/rohitkumar/Desktop/my-project/frontend/node_modules/.pnpm/sass@1.80.6/node_modules/sass/sass.dart.js:4995:17)
    at /Users/rohitkumar/Desktop/my-project/frontend/node_modules/.pnpm/sass@1.80.6/node_modules/sass/sass.dart.js:20800:20
    at _wrapJsFunctionForAsync_closure.$protected (/Users/rohitkumar/Desktop/my-project/frontend/node_modules/.pnpm/sass@1.80.6/node_modules/sass/sass.dart.js:5020:15)
    at _wrapJsFunctionForAsync_closure.call$2 (/Users/rohitkumar/Desktop/my-project/frontend/node_modules/.pnpm/sass@1.80.6/node_modules/sass/sass.dart.js:37950:12)
    at _awaitOnObject_closure0.call$2 (/Users/rohitkumar/Desktop/my-project/frontend/node_modules/.pnpm/sass@1.80.6/node_modules/sass/sass.dart.js:37944:25)
    at _RootZone.runBinary$3$3 (/Users/rohitkumar/Desktop/my-project/frontend/node_modules/.pnpm/sass@1.80.6/node_modules/sass/sass.dart.js:39649:18)
    at _FutureListener.handleError$1 (/Users/rohitkumar/Desktop/my-project/frontend/node_modules/.pnpm/sass@1.80.6/node_modules/sass/sass.dart.js:38167:21)
    at _Future__propagateToListeners_handleError.call$0 (/Users/rohitkumar/Desktop/my-project/frontend/node_modules/.pnpm/sass@1.80.6/node_modules/sass/sass.dart.js:38482:49)
    at Object._Future__propagateToListeners (/Users/rohitkumar/Desktop/my-project/frontend/node_modules/.pnpm/sass@1.80.6/node_modules/sass/sass.dart.js:5217:77)
    at _Future._completeError$2 (/Users/rohitkumar/Desktop/my-project/frontend/node_modules/.pnpm/sass@1.80.6/node_modules/sass/sass.dart.js:38333:9)
    at _AsyncAwaitCompleter.completeError$2 (/Users/rohitkumar/Desktop/my-project/frontend/node_modules/.pnpm/sass@1.80.6/node_modules/sass/sass.dart.js:37931:12)
    at Object._asyncRethrow (/Users/rohitkumar/Desktop/my-project/frontend/node_modules/.pnpm/sass@1.80.6/node_modules/sass/sass.dart.js:4995:17)
    at /Users/rohitkumar/Desktop/my-project/frontend/node_modules/.pnpm/sass@1.80.6/node_modules/sass/sass.dart.js:86182:24
    at _wrapJsFunctionForAsync_closure.$protected (/Users/rohitkumar/Desktop/my-project/frontend/node_modules/.pnpm/sass@1.80.6/node_modules/sass/sass.dart.js:5020:15)
    at _wrapJsFunctionForAsync_closure.call$2 (/Users/rohitkumar/Desktop/my-project/frontend/node_modules/.pnpm/sass@1.80.6/node_modules/sass/sass.dart.js:37950:12)
    at _awaitOnObject_closure0.call$2 (/Users/rohitkumar/Desktop/my-project/frontend/node_modules/.pnpm/sass@1.80.6/node_modules/sass/sass.dart.js:37944:25)
    at _RootZone.runBinary$3$3 (/Users/rohitkumar/Desktop/my-project/frontend/node_modules/.pnpm/sass@1.80.6/node_modules/sass/sass.dart.js:39649:18)
    at _FutureListener.handleError$1 (/Users/rohitkumar/Desktop/my-project/frontend/node_modules/.pnpm/sass@1.80.6/node_modules/sass/sass.dart.js:38167:21)
    at _Future__propagateToListeners_handleError.call$0 (/Users/rohitkumar/Desktop/my-project/frontend/node_modules/.pnpm/sass@1.80.6/node_modules/sass/sass.dart.js:38482:49)
 @ ../../../node_modules/.pnpm/@kitconcept+volto-light-theme@5.0.1_@eeacms+volto-accordion-block@10.4.6_@kitconcept+volto-bu_x5bo2ca4vy463dmo6jnv33c3tm/node_modules/@kitconcept/volto-light-theme/src/theme/main.scss 8:6-600 22:17-24 26:7-21 58:25-39 59:36-47 59:50-64 63:6-73:7 64:54-65 64:68-82 70:42-53 70:56-70 72:21-28 83:0-570 83:0-570 84:22-29 84:33-47 84:50-64 61:4-74:5
 @ ../../../node_modules/.pnpm/@kitconcept+volto-light-theme@5.0.1_@eeacms+volto-accordion-block@10.4.6_@kitconcept+volto-bu_x5bo2ca4vy463dmo6jnv33c3tm/node_modules/@kitconcept/volto-light-theme/src/customizations/@root/theme.js 5:0-55
 @ ./src/start-client.jsx 6:0-21
 @ ./src/client.js 3:0-36 4:0-6

webpack 5.90.1 compiled with 1 error in 9013 ms

```
git diff

```
index e256491..1598f9f 100644
--- a/frontend/packages/volto-my-project/package.json
+++ b/frontend/packages/volto-my-project/package.json
@@ -26,7 +26,12 @@
     "release-major-alpha": "release-it major --preRelease=alpha",
     "release-alpha": "release-it --preRelease=alpha"
   },
-  "dependencies": {},
+  "addons": [
+    "@kitconcept/volto-light-theme"
+  ],
+  "dependencies": {
+    "@kitconcept/volto-light-theme": "^5.0.1"
+  },
   "peerDependencies": {
     "react": "18.2.0",
     "react-dom": "18.2.0"

```

Volto: "version": "18.0.0",
VLT: 5.0.1

**Comment by sneridagh** [comment]
@mactrash If you don't give us the error, we cannot do anything. The config in your first comment looks fine. In the second, you didn't remove the placeholder "your_policy_addon_here". 

We improved a bit the docs: https://volto-light-theme.readthedocs.io/

@iRohitSingh It seems you forgot to declare the theme in `volto.config.js`.

```const addons = ['@kitconcept/volto-light-theme'];
const theme = '@kitconcept/volto-light-theme';

module.exports = {
addons,
theme,
};
```

**Comment by stevepiercy** [comment]
@sneridagh in https://volto-light-theme.readthedocs.io/install.html we make a lot of assumptions that folks might not understand. Maybe we should add a link to https://6.docs.plone.org/volto/development/add-ons/install-an-add-on.html. Note that the commands are not displaying, but will soon as we merge https://github.com/plone/documentation/pull/1770. You can see how it will look in this preview: https://plone6--1770.org.readthedocs.build/volto/development/add-ons/install-an-add-on.html

**Comment by mactrash** [comment]
@sneridagh may I know what is ""your_policy_addon_here""

**Comment by mactrash** [comment]
@sneridagh 

While I change the volto.config.js 

to
const theme = '@kitconcept/volto-light-theme';

module.exports = {
addons,
theme,
};

It result

/mnt/HDD2/VOLTO/test-com/frontend/core/packages/volto:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @plone/volto@18.1.0 start: `make build-deps && razzle start`
Exit status 1
 ELIFECYCLE  Command failed with exit code 1.

**Comment by stevepiercy** [comment]
> @sneridagh may I know what is ""your_policy_addon_here""

He means remove that line from your `addons` array in `/frontend/package.json`. It is intended as a placeholder for the name of a policy add-on that you might create.

I can't speak to the latest error message, as you need to provide a complete console output that includes the commands you used. IOW, help us reproduce the issue you experience.

**Comment by kittauri** [comment]
@mactrash, i dont know if it still relevant for you but maybe for all others who stumble across it. 
The problem is, that you put the dependecies and the addons into the wrong ```package.json```. 
See the end of this post for a visualisation of the project structure.

Be aware if you youst install a Plone project with ```pipx run cookieplone project``` you get Volto 18 as default.
What you are trying to do is installing Volto Light Theme and some Add-ons.

Documentation for Volto Light Theme:
https://volto-light-theme.readthedocs.io/install.html

## Solution

Path to the right ```package.json```

```frontend/packages/<volto-my-project>/package.json```

## Project Structure

```
.
├── backend/
├── CHANGELOG.md
├── dependabot.yml
├── devops/
├── docker-compose.yml
├── frontend
│ ├── core
│ │ ├── apps/
│ │ ├── CODE_OF_CONDUCT.md
│ │ ├── CONTRIBUTING.md
│ │ ├── docs/
│ │ ├── g-api/
│ │ ├── LICENSE.md
│ │ ├── lint-staged.config.js
│ │ ├── logos/
│ │ ├── Makefile
│ │ ├── package.json                    # Wrong package.json (Its for Volto Core)
│ │ ├── packages/
│ │ ├── PACKAGES.md
│ │ ├── patches/
│ │ ├── pnpm-lock.yaml
│ │ ├── pnpm-workspace.yaml
│ │ ├── README.md
│ │ ├── RELEASING.md
│ │ ├── requirements-docs.txt
│ │ ├── SECURITY.md
│ │ ├── styles/
│ │ ├── tsconfig.json
│ │ └── variables.mk
│ ├── cypress/
│ ├── cypress.config.js
│ ├── Dockerfile
│ ├── jest-addon.config.js
│ ├── Makefile
│ ├── mrs.developer.json
│ ├── node_modules/
│ ├── package.json                    # <-- Wrong package.json (I guess you put it in here)
│ ├── packages
│ │ └── volto-my-project                    # <-- Your project (where you most of the time will work when you do something with the frontend)
│ │ ├── babel.config.js
│ │ ├── CHANGELOG.md
│ │ ├── locales/
│ │ ├── news/
│ │ ├── node_modules
│ │ ├── package.json                    # <-- Right package.json (you should put in addons list here)
│ │ ├── public/
│ │ ├── src/
│ │ ├── towncrier.toml
│ │ └── tsconfig.json
│ ├── pnpm-lock.yaml
│ ├── pnpm-workspace.yaml
│ ├── public/
│ ├── README.md
│ └── volto.config.js
├── Makefile
├── public/
├── README.md
└── version.txt
```

**Comment by mactrash** [comment]
@kittauri 

I am now find in the right package.json and added

"addons": [
    // other add-ons installed
    "@eeacms/volto-accordion-block",
    "@kitconcept/volto-button-block",
    "@kitconcept/volto-dsgvo-banner",
    "@kitconcept/volto-heading-block",
    "@kitconcept/volto-introduction-block",
    "@kitconcept/volto-highlight-block",
    "@kitconcept/volto-separator-block",
    "@kitconcept/volto-slider-block",
    "@kitconcept/volto-light-theme",
  ],

Result error

Than I remove the , in the end and it don't show error

"addons": [
    "@eeacms/volto-accordion-block",
    "@kitconcept/volto-button-block",
    "@kitconcept/volto-dsgvo-banner",
    "@kitconcept/volto-heading-block",
    "@kitconcept/volto-introduction-block",
    "@kitconcept/volto-highlight-block",
    "@kitconcept/volto-separator-block",
    "@kitconcept/volto-slider-block",
    "@kitconcept/volto-light-theme" 
  ],  

But when I try to start the frontend it do error

/home/test/test/frontend/core/packages/volto:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @plone/volto@18.21.0 start: `make build-deps && razzle start`
Exit status 1
 ELIFECYCLE  Command failed with exit code 1.

Can you give me more tips how can I fix this?

Thx

**Comment by kittauri** [comment]
@mactrash 

Sure. Just to be sure, i have some questions for you: How did you install Plone ? Is it a fresh install ? Which command did you use after updating your addon list ?

I created a fresh installation using uvx as a reference for you.

1) Install uv (uvx is included)
2) Install Plone with the following command:

```uvx cookieplone```

3) Use default setting except for name  (i used mactrash-addon, see screenshot)
4) open code editor and edit ```package.json``` and ```volto.config.js```
5) run the command ```make install``` (from the root directory of the whole project)
6) for development start backend with ```make backend-start``` and in another terminal ```make frontend-start```

    - Note: if you dont have the make command because you are on Windows, just look into the Makefiles (see screeenshot) and do the commands manually. There are three Makefiles, one global, and then one for backend and one for frontend.

Screenshot:

![Image](https://github.com/user-attachments/assets/d9315388-63f2-4879-a43d-1e22306e8721)
